var catchphrases = ["I'm too old for this shit",
"JAMBALAYA",
"So's your face",
"How you doin'?",
"What'choo talkin' 'bout, Willis?",
"And that's the way it is.",
"Who are you wearing?",
"It's gonna be legen — wait for it — dary.",
"Danger, Will Robinson!",
"To the Batmobile!",
"Sock it to me!",
"Dy-no-mite!",
"Eat my shorts.",
"No soup for you!",
"Holy crap!",
"Will you accept this rose?",
"You're fired!",
"Everybody lies.",
"Bazinga!",
"Aaaaw, hell na",
"Do you want to get Ants? Because this is how you get Ants",
"Danger Zone",
"Dumbass",
"THAT'S WHAT SHE SAID!",
"I'm the only gay in the village",
"I have a cunning plan",
"Is it because I is black?",
"Life? Dont talk to me about Life!",
"I'M A WHALE",
"IT's OVER NINE THOUSAND",
"We've got so many dead bodies we're hanging 'em from the ceiling!",
"I'M BLUE DABADEE DABADY DA-BA-DEEE DA-BA DY",
"Ya nan",
"420swag"]