//Mercilessly stolen from Wikipedia, plus a couple of random ones of my own.
var possibleAnswers = [
    "It is certain.",
    "It is decidedly so.",
    "Without a doubt.",
    "Yes, definitely.",
    "You may rely on it.",
    "As I see it, yes.",
    "Most likely.",
    "The outlook is good.",
    "Yes.",
    "Signs point to yes.",
    "Reply hazy, try again.",
    "Ask again later.",
    "Better not tell you now.",
    "Cannot predict now.",
    "Concentrate and ask again.",
    "Don't count on it.",
    "My reply is no.",
    "My sources say no.",
    "The outlook is not so good.",
    "Very doubtful",
    "There is no spoon.",
    "You will have to wait.",
    "Are you kidding?",
    "Don't bet on it.",
    "Forget about it."
];
